AWSTemplateFormatVersion: '2010-09-09'
Description: Stack STD21038

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: STD21038
  BucketArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: STD21038/s3/bucket-arn
      Type: String
      Value: !GetAtt Bucket.Arn
  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: STD21038/s3/bucket-name
      Type: String
      Value: !Ref Bucket