AWSTemplateFormatVersion: 2010-09-09
Description: Storage stack STD21038

Parameters:
  DBName:
    Type: String
    Default: db21038
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.

Resources:
  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: "5"
      DBInstanceClass: !Ref DBClass
      Engine: postgres
      MasterUsername: !Sub "{{resolve:ssm:/shared/db/username}}"
      MasterUserPassword: !Sub "{{resolve:ssm:/shared/db/password}}"
  DatabaseSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /shared/db/url
      Type: String
      Value:
        !Join [
          "",
          [
            jdbc:postgresql://,
            !GetAtt Database.Endpoint.Address,
            ":",
            !GetAtt Database.Endpoint.Port,
            "/",
            !Ref DBName,
          ],
        ]
Outputs:
  DatabaseName:
    Value: !Ref Database
