AWSTemplateFormatVersion: '2010-09-09'
Description: Stack STD21038

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: STD21038
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref Bucket